### ISSUE TITLE
Git ignored folders are not displayed differently

### ISSUE THREAD

**Issue by lgraziani2712** [RosinaGala/pullers#1]
Hein theme:
![image](https://user-images.githubusercontent.com/15050200/74030425-c86ca080-498d-11ea-9ab9-3efdd30b8ca7.png)

Dark (official VSCode theme): 
![image](https://user-images.githubusercontent.com/15050200/74030463-e63a0580-498d-11ea-8f65-93a9e1e2fccc.png)

BTW, thank you for theme! I really love it!

**Comment by sinacodes** [comment]
Hi @lgraziani2712 
thank you for the feedback!
I fixed this issue with the next version
